allow_help=1
allow_commands=1
allow_status=1
allow_log=1
allow_caps=1
allow_submit=1
allow_process=1
allow_results=1
allow_shell=0
allow_reboot=0
allow_debug=1
allow_daemons=1
allow_poweroff=0
allow_prune=1
allow_rotate_logs=1
